### ISSUE TITLE
后端搭建问题

### ISSUE THREAD

**Issue by 83838395** [subei12/team_oa#2]
这个葫芦侠oa系统后端怎么搭建，前端会后端上传源码解析之后还是404

**Comment by subei12** [comment]
这是个java项目，无法像PHP等项目直接上传源码解析使用。
推荐使用maven打成jar包运行

**Comment by subei12** [comment]
如确需使用，晚点我会把sql脚本更新到仓库

**Comment by 83838395** [comment]
> 如确需使用，晚点我会把sql脚本更新到仓库

我确定使用，java的不用去用能不能出个教程
