### ISSUE TITLE
默认的账号密码是什么

### ISSUE THREAD

**Issue by au-top** [subei12/team_oa#3]

**Comment by subei12** [comment]
账号密码都是：superAdmin

**Comment by au-top** [comment]
好的非常感谢
配置文件中的 hlx.key.url 指的是什么

**Comment by subei12** [comment]
“葫芦侠三楼社区” 的可以获取key的接口，可以抓账户密码登录的接口，也可以是QQ登录的接口。
如果你不是在葫芦侠相关的地方用，那这个参数不填也没事。

**Comment by au-top** [comment]
好的非常感谢
